{% set name = "pyiron_workflow" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: be005873f3e551d45bd5f66663a1a94cfab7759d87fe7cb55d0a3f59998d51d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - h5io >=0.2.2
    - h5io_browser >=0.0.9
    - pyiron_contrib >=0.1.15
    - pympipool >=0.7.13
    - python >=3.10
    - bidict >=0.22.1
    - cloudpickle >=3.0.0
    - python-graphviz >=0.20.1
    - matplotlib-base >=3.8.2
    - toposort >=1.10
    - typeguard >=4.1.5

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
