{% set name = "pyiron_workflow" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: e1e960fbb9ce41283d007122e00417e7d7c1771f873a47a1e7684421e4386a31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - toml
    - versioneer
    - bidict
    - cloudpickle
    - executorlib
    - pandas
    - pyiron_snippets
    - python-graphviz
    - toposort
    - typeguard
  run:
    - python >=3.10,<3.13
    - bidict >=0.23.0,<=0.23.1
    - cloudpickle >=3.0.0,<3.1.0
    - executorlib >=0.0.1,<=0.0.2
    - pandas >=2.2.0,<2.3.0
    - pyiron_snippets ==0.1.4
    - python-graphviz >=0.20.0,<=0.20.3
    - toposort ==1.10
    - typeguard >=4.2.0,<4.4.0

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
