{% set python_min = "3.10" %}
{% set name = "pyiron_workflow" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: 5b83603bd2cda00017f2f96b3f189cdca670dffec2411ef95adf9608b3c42961

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - toml
    - versioneer
    - bidict
    - cloudpickle
    - executorlib
    - pandas
    - pint
    - pyiron_snippets
    - python-graphviz
    - toposort
    - typeguard
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - bidict >=0.23.0,<=0.23.1
    - cloudpickle >=3.0.0,<3.2.0
    - executorlib >=0.0.1,<1.5.0
    - pandas >=2.2.0,<2.4.0
    - pint >=0.23.0,<=0.24.4
    - pyiron_snippets >=0.1.4,<=0.2.0
    - python-graphviz >=0.20.0,<=0.20.3
    - toposort ==1.10
    - typeguard >=4.2.0,<4.5.0

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
