{% set python_min = "3.11" %}
{% set name = "pyiron_workflow" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: 1b77d03af39d5f1b6dffb723f90c3f66b21b08a86e09383164124caed447b29a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - toml
    - versioneer
    - bagofholding
    - bidict
    - cloudpickle
    - executorlib
    - pandas
    - pint
    - pyiron_snippets
    - python-graphviz
    - rdflib
    - semantikon
    - toposort
    - typeguard
    - setuptools
  run:
    - rdflib >=7.1.4,<7.2.0
    - semantikon ==0.0.22
    - bagofholding >=0.1.0,<=0.1.4
    - python >={{ python_min }},<3.14
    - bidict ==0.23.1
    - cloudpickle >=3.0.0,<3.2.0
    - executorlib >=1.5.3,<1.8.0
    - pandas >=2.2.2,<2.4.0
    - pint >=0.24,<=0.25
    - pyiron_snippets >=0.1.4,<=0.2.0
    - python-graphviz >=0.20.3,<=0.21
    - toposort ==1.10
    - typeguard >=4.2.0,<4.5.0

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
