{% set name = "pyiron_workflow" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: 479b4ee5cec1e8df7088bafa21132aad95b29d01f0991a769e855e3d4c5716a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - toml
    - versioneer
    - pandas
    - pyiron_base
    - h5io
    - h5io_browser
    - pyiron_contrib
    - pympipool
    - bidict
    - cloudpickle
    - python-graphviz
    - matplotlib-base
    - toposort
    - typeguard
  run:
    - pyiron_snippets >=0.1.0,<=0.1.3
    - pandas >=2.2.0,<2.3.0
    - pyiron_base >=0.8.3,<=0.9.10
    - h5io >=0.2.2,<=0.2.4
    - h5io_browser >=0.0.12,<=0.0.16
    - pyiron_contrib >=0.1.16,<=0.1.17
    - pympipool >=0.8.0,<=0.9.1
    - python >=3.10,<3.13
    - bidict >=0.23.0,<=0.23.1
    - cloudpickle >=3.0.0,<3.1.0
    - python-graphviz >=0.20.0,<=0.20.3
    - matplotlib-base >=3.8.4,<3.9.0
    - toposort ==1.10
    - typeguard >=4.2.0,<4.4.0

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
