{% set name = "pyiron_workflow" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: b1dc9581fef4d3ec4946ea798544ac02f54eabecf1ca8e961194d4e5e15929c5
  patches:
    - versioneer.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bidict >=0.22.1
    - cloudpickle >=2.2.1
    - python-graphviz >=0.20.1
    - maggma >=0.57.1
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0
    - pyiron_atomistics >=0.3.4
    - pyiron_base >=0.6.7
    - toposort >=1.10
    - typeguard >=4.1.5

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
