{% set name = "pyiron_workflow" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: eb257238079a2e2ef59a08a947cea6091fc4b6dd6b54cc2b8ec9a66fb2dc6aec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - pyiron_base >=0.8.3
    - h5io >=0.2.2
    - h5io_browser >=0.0.12
    - pyiron_contrib >=0.1.16
    - pympipool >=0.8.0
    - python >=3.10
    - bidict >=0.23.1
    - cloudpickle >=3.0.0
    - python-graphviz >=0.20.3
    - matplotlib-base >=3.8.4
    - toposort >=1.10
    - typeguard >=4.2.1

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
